name: hawk
description:
  This package provides an event driven system for your application.
version: 0.0.1+1
repository: https://github.com/wim07101993/hawk

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  async: ^2.9.0
  behaviour: ^0.0.2

dev_dependencies:
  lint: ^1.8.2
  test: ^1.21.3
